#include <cstdint>
#include <iostream>

enum class teamUpBonus : std::uint_fast8_t
{
	bonus1_2_4,
	bonus2_4_6,
	bonus2_4_7,
	bonus2_4_8,
	bonus3_6_10,
	
	NewAvengers,
	GuardiansOfTheGalaxy,
	FemmeFatalis,
	AgentsOfSHIELD,
	X_Men,
	Villians,
	Defenders,
	Anti_Heroes,
	OriginalAvengers,
	MidnightSons,
	WebWarriors,
	TheCrew,
	MarvelRoyalty,
	GodsAndDeamons,
	Generations,
	HeavyHitters,
	AgileFighters,
	UltimateAllience3,
	Avengers,
	X_Force,
	WomenOfMarvel,
	FamilyValues,
	Partners,
	BackInBlack,
	MartialArtists,
	ForcesOfNature,
	CuttingEdge,
	BigBrains,
	WisecrackingWarriors,
	TeamLeaders,
	All_NewX_Men,
	SharpShooters,
	HeavyMetal,
	MarvelKnights,
	FirstClassX_Men,
	FantasticFour,
	FantasticFourReserveMembers,
	SmoothOperators
};